# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-09-24 10:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_foodtype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodtype',
            name='childtypenames',
            field=models.CharField(max_length=200),
        ),
    ]
