# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-09-25 12:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20180924_2224'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='u_mail',
            field=models.CharField(default=1, max_length=40, unique=True),
            preserve_default=False,
        ),
    ]
