# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-09-25 12:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_usermodel_u_mail'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='u_pass',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
